<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
<link rel="icon" type="image/png" href="http://www.hta.org/images/icon.png"/>
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<meta name="generator" content="Adobe GoLive" />
		<title>About the trip planner and terms & conditions of service from Eureka Transit Service</title>
		<link href="css/main.css" rel="stylesheet" type="text/css" media="all" />

<style type="text/css">
#instruction {float:left; width:200px;height:300px;margin-left:10px;margin-right:10px;}
li {margin-left:20px; padding-right:7px;}
#zone_name {text-align:center; font-size:20px; line-height:25px; width:40px; font-weight:bold;padding:0px}
td {border-bottom:1px solid #ccc;padding:1px;padding-right:10px}
</style>

<script type="text/javascript">
</script>

</head>

<body>

<a href="#Content" class="hidden">Skip to Content</a>
<div id="Container">
<div id="ContentWrapper">




<div id="logo_header">
<a href="index.php"><img src="images/ets_logo.gif" alt="" border="0" width="206" height="81" /></a>
</div>

<div id="header_area">

<div id="nav_path"><a href="index.php">ETS Home</a> ></div>

<br clear="left"/>

<h1 id="page_title">About the Trip Planner and Terms and Conditions</h1>

</div>

<br clear="all">

<hr size="2"  width="784" style="padding-left:10px;padding-right:10px;">

<div id="page_text_itself">

<div style="float:left;margin-right:20px">
<p>The trip planner featured on this site is powered by <a href="http://www.google.com/transit">Google Transit</a>.</p>

<h3>Humboldt County transit systems in Google Transit</h3>

<p>Google Transit is a trip planner to help transit riders find their way from points A to B across multiple transit systems, including these in our area:</p>

<ul>
<li>Redwood Transit System</li>
<li>Eureka Transit Service</li>
<li>Arcata and Mad River Transit Service</li>
</ul>

<h3>Terms and conditions</h3>

<p>We're working hard to provide quality information through Google Transit, but we can't guarantee 100% accuracy.  Use the trip planner as a first step for planning purposes only.  Neither this transit agency, nor any other, nor the designer of this site, will be held responsible for any mishap which may result from using Google Transit itineraries.  Bear in mind this is a new and experimental service that is still being refined both by Google and participating transit agencies.  Also see the <a href="http://www.google.com/intl/en_us/help/terms_transit.html">Google Transit Terms and Conditions</a>.</p>

<h3>How much should I depend on trip itineraries generated by Google Transit?</h3>

<p>Since Google Transit is an experimental offering from Google Labs, and since Humboldt-area transit agency participation in Google Transit is also in the preliminary stages, we recommend riders double-check trip itineraries with the printed bus schedules and other sources.  We've made great efforts to provide reliable data, but neither Google Transit nor this transit agency can guarantee your trip itinerary will be perfect.</p>

<h3>Known issues:</h3>

<ul>
<li>Routes are drawn as straight lines from stop to stop, and do not follow the actual route of the bus on the roads.  We are working to improve this.</li>
<li>Walking directions and times can be inaccurate, sometimes suggesting walking paths across un-passable obstacles.  Google is working to improve walking directions.</li>
</ul>

<p>Other known issues may be discussed in the <a href="http://groups.google.com/group/humboldt-google-transit">Google Transit for Humboldt County, CA discussion group</a>.</p>

<h3>What should I do if I receive incorrect, misleading, or confusing trip itinerary information?</h3>
<p>If your trip itinerary has inaccurate stop location, time, fare, or service schedule information, it's probably because of an error in the information this or another transit agency has provided to Google Transit.  Record the start address, end address, and arrival/departure date & time for your itinerary and contact the appropriate transit agency to tell them about the problem so it can be fixed.</p>

<p>If your problem is with inaccurate or misleading walking directions, awkward transfers, or any problem with the visual map and route display, your issue is probably best addressed directly to Google.  See the FAQ from Google, <a href="http://www.google.com/intl/en_us/help/faq_transit.html#reporting_issues">"Google Transit Trip Planner isn't doing what I expected. Who needs to know?"</a>.  If you email your problem to <a href="mailto:labs-transit_feedback@google.com">labs-transit_feedback@google.com</a>, you might also carbon-copy (cc:) transit agency staff in on your email, so they can be made aware.  You can search the discussions in the <a href="http://groups.google.com/group/humboldt-google-transit">Google Transit for Humboldt County, CA discussion group</a> to see if anyone else has experienced the same problem.  If your search returns no results, please describe your issue in a post to this group.</p>

<h3>More about Google Transit</h3>
<ul>
<li><a href="http://www.google.com/intl/en_us/help/faq_transit.html">Google Transit FAQ</a></li>
<li><a href="http://groups.google.com/group/googletransit">Google Transit forum</a></li>
</ul>

</div>



</div>

</div>
<br clear="all" />
</div>

<?php require_once ('includes/footer.html'); ?>


</body>

</html>